[phases.setup]
nixPkgs = ["nodejs", "nodejs-slim"]

[phases.install]
cmds = ["npm install --omit=dev"]

[phases.build]
cmds = ["echo 'No build step required'"]

[start]
cmd = "node -r dotenv/config --experimental-json-modules src/index.js"

[variables]
NODE_ENV = "production" 