[build]
builder = "nixpacks"
buildCommand = "npm install --only=prod"

[deploy]
startCommand = "node -r dotenv/config --experimental-json-modules src/index.js"
healthcheckPath = "/"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[phases.setup]
nixPkgs = ["nodejs-18_x", "nodejs-19_x"]

[phases.install]
cmds = ["npm install --omit=dev"]

[phases.build]
cmds = ["echo 'No build step required'"] 