"""Initial migration - all models

Revision ID: 2177016e080f
Revises: 
Create Date: 2025-11-03 10:59:08.726186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2177016e080f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('school_id', sa.Text(), nullable=False),
    sa.Column('school_name', sa.Text(), nullable=False),
    sa.Column('school_type', sa.Text(), nullable=True),
    sa.Column('board', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('pincode', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.Text(), nullable=True),
    sa.Column('contact_phone', sa.Text(), nullable=True),
    sa.Column('principal_name', sa.Text(), nullable=True),
    sa.Column('principal_phone', sa.Text(), nullable=True),
    sa.Column('classes_offered', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('total_students', sa.Integer(), nullable=True),
    sa.Column('total_teachers', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('subscription_plan', sa.Text(), nullable=True),
    sa.Column('subscription_expires_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('school_id')
    )
    op.create_table('audit_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('school_id', sa.Text(), nullable=True),
    sa.Column('action_type', sa.Text(), nullable=False),
    sa.Column('resource_type', sa.Text(), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('ai_model', sa.Text(), nullable=True),
    sa.Column('ai_input', sa.Text(), nullable=True),
    sa.Column('ai_output', sa.Text(), nullable=True),
    sa.Column('ai_confidence', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('bias_detected', sa.Boolean(), nullable=True),
    sa.Column('bias_type', sa.Text(), nullable=True),
    sa.Column('bias_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('ip_address', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_duration', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('classes',
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.Text(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=True),
    sa.Column('class_name', sa.Text(), nullable=False),
    sa.Column('class_level', sa.Integer(), nullable=False),
    sa.Column('section', sa.Text(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('total_students', sa.Integer(), nullable=True),
    sa.Column('academic_year', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ),
    sa.PrimaryKeyConstraint('class_id')
    )
    op.create_table('profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('role', sa.Enum('STUDENT', 'TEACHER', 'CLASS_TEACHER', 'PRINCIPAL', 'SCHOOL_ADMIN', name='userrole'), nullable=False),
    sa.Column('school_id', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('user_type', sa.Text(), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_login', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profiles_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_profiles_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_profiles_school_id'), ['school_id'], unique=False)

    op.create_table('analytics',
    sa.Column('analytics_id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.Text(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=True),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('teacher_id', sa.UUID(), nullable=True),
    sa.Column('metric_type', sa.Text(), nullable=False),
    sa.Column('metric_name', sa.Text(), nullable=False),
    sa.Column('metric_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('class_level', sa.Integer(), nullable=True),
    sa.Column('time_period', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.class_id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ),
    sa.PrimaryKeyConstraint('analytics_id')
    )
    op.create_table('assignments',
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.Text(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('class_level', sa.Integer(), nullable=False),
    sa.Column('upload_type', sa.Text(), nullable=True),
    sa.Column('upload_url', sa.Text(), nullable=True),
    sa.Column('upload_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('questions_per_student', sa.Integer(), nullable=True),
    sa.Column('max_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('passing_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('is_personalized', sa.Boolean(), nullable=True),
    sa.Column('personalization_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('question_pool', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('assigned_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('due_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.class_id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_table('lesson_plans',
    sa.Column('lesson_plan_id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.Text(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('class_level', sa.Integer(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('objectives', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('activities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('materials_needed', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('source_upload_id', sa.UUID(), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=True),
    sa.Column('generation_prompt', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('academic_year', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.class_id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ),
    sa.PrimaryKeyConstraint('lesson_plan_id')
    )
    op.create_table('student_enrollments',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.Text(), nullable=False),
    sa.Column('enrolled_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.class_id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ),
    sa.PrimaryKeyConstraint('student_id', 'class_id')
    )
    op.create_table('student_profiles',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.Text(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=True),
    sa.Column('overall_performance', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('subject_mastery', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('personality_type', sa.Text(), nullable=True),
    sa.Column('learning_pace', sa.Text(), nullable=True),
    sa.Column('strengths', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('weaknesses', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('engagement_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('completion_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('avg_time_per_assignment', sa.Integer(), nullable=True),
    sa.Column('preferred_difficulty', sa.Text(), nullable=True),
    sa.Column('preferred_question_types', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('profile_version', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.class_id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_table('student_assignments',
    sa.Column('student_assignment_id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('assigned_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('submitted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('graded_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.assignment_id'], ),
    sa.PrimaryKeyConstraint('student_assignment_id')
    )
    op.create_table('submissions',
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('student_assignment_id', sa.UUID(), nullable=True),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.Text(), nullable=False),
    sa.Column('submission_type', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('files', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('ocr_confidence', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('time_taken', sa.Integer(), nullable=True),
    sa.Column('device_type', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('graded_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.assignment_id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ),
    sa.ForeignKeyConstraint(['student_assignment_id'], ['student_assignments.student_assignment_id'], ),
    sa.PrimaryKeyConstraint('submission_id')
    )
    op.create_table('grades',
    sa.Column('grade_id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=True),
    sa.Column('school_id', sa.Text(), nullable=False),
    sa.Column('score', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('max_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('percentage', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('grade', sa.Text(), nullable=True),
    sa.Column('ai_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('ai_confidence', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('manual_override', sa.Boolean(), nullable=True),
    sa.Column('teacher_feedback', sa.Text(), nullable=True),
    sa.Column('teacher_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('question_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('flagged', sa.Boolean(), nullable=True),
    sa.Column('flag_reason', sa.Text(), nullable=True),
    sa.Column('graded_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('published_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.assignment_id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.submission_id'], ),
    sa.PrimaryKeyConstraint('grade_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grades')
    op.drop_table('submissions')
    op.drop_table('student_assignments')
    op.drop_table('student_profiles')
    op.drop_table('student_enrollments')
    op.drop_table('lesson_plans')
    op.drop_table('assignments')
    op.drop_table('analytics')
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profiles_school_id'))
        batch_op.drop_index(batch_op.f('ix_profiles_role'))
        batch_op.drop_index(batch_op.f('ix_profiles_email'))

    op.drop_table('profiles')
    op.drop_table('classes')
    op.drop_table('audit_logs')
    op.drop_table('schools')
    # ### end Alembic commands ###

